### PR TITLE
Snippets for qiskit-terra 

### PR DESCRIPTION
**Pull request by AkashGutha**
### Summary
- Added four basic snippets for the terra package, picked up directly from [my extension](https://github.com/AkashGutha/Qiskit-Snippets)

### Details and comments
- The snippets are aimed to give the users a headstart, sparing them from the repetitive task of writing skeleton code again and again.

### CODE REVIEW

**Comment by cbjuan** [comment]
Hi @AkashGutha! As we talked in @atilag in the Qiskit Slack, we should wait before merging the PR. Qiskit team plans to release the Qiskit-terra 0.6 version in a few days, and the changes introduced can be relevant for the snippets.

**Comment by AkashGutha** [comment]
@cbjuan sure!

**Comment by cbjuan** [comment]
Hi @AkashGutha. Sure, finally we are working on updating the extension to use Qiskit-terra >6 and we will review your PR in parallel to our changes.

**Comment by cbjuan** [comment]
Hi @AkashGutha! We now have the PR #47 where we are adding the support of qiskit-terra >v0.6. We will maintain you informed about our progress, and when we finish the update of the extension, we will take a final look on your PR and merge it ASAP.

**Comment by cbjuan** [comment]
Thanks for tackling the changes proposed, @AkashGutha! Proceeding to merge the PR and adding it to the CHANGELOG for the next release.

And congrats for your first contribution to this repository. We hope to collaborate with you again in future contributions 👍

**Comment by AkashGutha** [comment]
@cbjuan I definitely will. Cheers!

**Pull request merged**
